// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// TODO don't use animated icons
func weather_forecast() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!--<div class=\"flex-1 flex flex-col\">\n\t\t<div class=\"flex-1 flex flex-row gap-4 justify-center items-center\">\n\t\t\t<img src=\"/assets/icons/weather/clear-day.svg\" class=\"h-96\"/>\n\t\t\t<span class=\"text-[15rem]\">80<span class=\"text-9xl\">°F</span></span>\n\t\t\t<span class=\"text-9xl ml-8\">{ \"@\" }</span>\n\t\t\t<span class=\"text-[15rem]\">2</span>\n\t\t</div>--><div class=\"flex-1 flex flex-row gap-28 justify-center\"><div class=\"flex flex-col items-center\"><span class=\"flex-1 text-[7rem] leading-[6rem] font-bold\">12<span class=\"text-[4rem]\">PM</span></span> <img src=\"/assets/icons/weather/clear-day.svg\" class=\"flex-1 h-48\"> <span class=\"flex-1 text-[9rem] leading-[8rem]\">80</span></div><div class=\"flex flex-col items-center\"><span class=\"flex-1 text-[7rem] leading-[6rem] font-bold\">1<span class=\"text-[4rem]\">PM</span></span> <img src=\"/assets/icons/weather/clear-day.svg\" class=\"flex-1 h-48\"> <span class=\"flex-1 text-[9rem] leading-[8rem]\">82</span></div><div class=\"flex flex-col items-center\"><span class=\"flex-1 text-[7rem] leading-[6rem] font-bold\">2<span class=\"text-[4rem]\">PM</span></span> <img src=\"/assets/icons/weather/clear-night.svg\" class=\"flex-1 h-48\"> <span class=\"flex-1 text-[9rem] leading-[8rem]\">85</span></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
